allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@inquirer/ansi@2.0.6'
  - '@inquirer/checkbox@5.2.0'
  - '@inquirer/confirm@6.1.0'
  - '@inquirer/core@11.2.0'
  - '@inquirer/editor@5.2.0'
  - '@inquirer/expand@5.1.0'
  - '@inquirer/external-editor@3.0.1'
  - '@inquirer/figures@2.0.6'
  - '@inquirer/input@5.1.0'
  - '@inquirer/number@4.1.0'
  - '@inquirer/password@5.1.0'
  - '@inquirer/prompts@8.5.0'
  - '@inquirer/rawlist@5.3.0'
  - '@inquirer/search@4.2.0'
  - '@inquirer/select@5.2.0'
  - '@inquirer/type@4.0.6'
  - inquirer@14.0.0
